// <auto-generated />
using System;
using CarRent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRent.Data.Migrations
{
    [DbContext(typeof(CarDataContext))]
    partial class CarDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarRent.Models.CarsModel", b =>
                {
                    b.Property<int>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<double>("Combustion");

                    b.Property<string>("Package");

                    b.Property<int>("ProductionYear");

                    b.Property<string>("Type");

                    b.HasKey("IdCar");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarRent.Models.ClientModel", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Discount");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("SecondName");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CarRent.Models.OrdersModel", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdCar");

                    b.Property<int>("IdClient");

                    b.Property<DateTime>("OrderDateFrom");

                    b.Property<DateTime>("PayDate");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("ReturnDate");

                    b.Property<byte>("Score");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdCar");

                    b.HasIndex("IdClient");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CarRent.Models.OrdersModel", b =>
                {
                    b.HasOne("CarRent.Models.CarsModel", "Cars")
                        .WithMany()
                        .HasForeignKey("IdCar")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarRent.Models.ClientModel", "Clients")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
