// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using panda3.Data;
using System;

namespace panda3.Data.Migrations
{
    [DbContext(typeof(KomputerDbContext))]
    partial class KomputerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("panda3.Models.KartaGraficznaModel", b =>
                {
                    b.Property<int>("ProcesorID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazwa");

                    b.HasKey("ProcesorID");

                    b.ToTable("KartaGraficzna");
                });

            modelBuilder.Entity("panda3.Models.KomputerModel", b =>
                {
                    b.Property<int>("KomputerID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cena");

                    b.Property<DateTime>("DataProdukcji");

                    b.Property<int>("KartagraficznaID");

                    b.Property<string>("Model");

                    b.Property<int>("PlytaglownaID");

                    b.Property<int>("ProcesorID");

                    b.Property<string>("Producent");

                    b.HasKey("KomputerID");

                    b.ToTable("Komputer");
                });

            modelBuilder.Entity("panda3.Models.PlytaGlownaModel", b =>
                {
                    b.Property<int>("PlytaGlownaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazwa");

                    b.HasKey("PlytaGlownaId");

                    b.ToTable("PlytaGlowna");
                });

            modelBuilder.Entity("panda3.Models.ProcesorModel", b =>
                {
                    b.Property<int>("ProcesorID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazwa");

                    b.HasKey("ProcesorID");

                    b.ToTable("Procesor");
                });

            modelBuilder.Entity("panda3.Models.RezerwacjaModel", b =>
                {
                    b.Property<int>("RezerwacjaID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataPrzedluzona");

                    b.Property<DateTime>("DataRozpoczecia");

                    b.Property<DateTime>("DataZakonczenia");

                    b.Property<int>("KomputerID");

                    b.Property<int>("UzytkownikID");

                    b.HasKey("RezerwacjaID");

                    b.ToTable("Rezerwacja");
                });

            modelBuilder.Entity("panda3.Models.UzytkownicyModel", b =>
                {
                    b.Property<int>("UzytkownikId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CzyAdmin");

                    b.Property<string>("Email");

                    b.Property<string>("Haslo");

                    b.Property<string>("Login");

                    b.HasKey("UzytkownikId");

                    b.ToTable("Uzytkownicy");
                });
#pragma warning restore 612, 618
        }
    }
}
